FROM nginx:latest

RUN mkdir -p /usr/share/nginx/html/
COPY nginx/index.html /usr/share/nginx/html/index.html

#RUN mkdir -p /usr/share/nginx/html/config/hello-world/
#COPY nginx/config/hello-world/hello-world.config /usr/share/nginx/html/config/hello-world/hello-world.config
#
#RUN mkdir -p /usr/share/nginx/html/files/hello-world/
#COPY nginx/files/hello-world/hello-world.tgz /usr/share/nginx/html/files/hello-world/hello-world.tgz
